runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/styles.*
  static_dir: static/styles
  login: required
- url: /static.*
  static_dir: static
  login: required
- url: /.*
  script: main.app
  login: required
# - url: /search.*
#   script: main.app
#   login: required
# - url: /result.*
#   script: main.app
#   login: required
# - url: /details.*
#   script: main.app
#   login: required
# - url: /history.*
#   script: main.app
#   login: required
# - url: /favorites.*
#   script: main.app
#   login: required
# - url: /aboutus.*
#   script: main.app
#   login: required

libraries:
- name: jinja2
  version: latest
